version: '3.6'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    container_name: path_app
    restart: unless-stopped
    tty: true
    ports:
      - ${PHP_FPM_PORT}:9000
    networks:
      - path-network
    depends_on:
      - mysql
  webserver:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: path_webserver
    restart: unless-stopped
    tty: true
    ports:
      - ${NGINX_PORT}:80
    networks:
      - path-network
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7.22
    container_name: path_mysql
    restart: unless-stopped
    tty: true
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - path-network

networks:
  path-network:
    driver: bridge
volumes:
  dbdata:
    driver: local
